### ISSUE TITLE
ModuleNotFoundError when running from annotate.online output to COCO input format

### ISSUE THREAD

**Issue by DenisKOMAROV** [superannotateai/annotateonline-input-converters#4]
Hello! I've been trying to use converter from annotate.online output to COCO input format with this command
```
python3 sa_to_coco.py -is ./my_dataset -sr 80 -ptype pixel -t instance_segmentation -dn my_dataset_name -od my_output_dir -cp True
```
And I'd got such error:
```
Traceback (most recent call last):
  File "sa_to_coco.py", line 11, in <module>
    from .sa_coco_converters.converters import Converter
ModuleNotFoundError: No module named '__main__.sa_coco_converters'; '__main__' is not a package
```
https://github.com/superannotateai/annotateonline-input-converters/blob/65028f8fb6ed68c3e43b164ee38ca82cacd1a438/sa_to_coco.py#L11

I'm not sure that this is the right solution, but It worked fine with this code in sa_to_coco.py
```
from sa_coco_converters.converters import Converter
```

**Comment by VavoTK** [comment]
Hi @DenisKOMAROV ,

Yes your fix is the correct one, this should be in the master branch already. Thanks for reporting it.
